name: deploy-foundryvtt

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *' # 2am NZT (UTC+12)
    
permissions:
  id-token: write
  contents: read

jobs:
  deploy-aas:
    if: vars.Type == 'AAS'
    uses: ./.github/workflows/deploy-aas.yml
    with:
      LOCATION: ${{ vars.LOCATION }}
      BASE_RESOURCE_NAME: ${{ vars.BASE_RESOURCE_NAME }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      STORAGE_CONFIGURATION: ${{ vars.STORAGE_CONFIGURATION }}
      APPSERVICEPLAN_CONFIGURATION: ${{ vars.APPSERVICEPLAN_CONFIGURATION }}
      DEPLOY_DDBPROXY: ${{ vars.DEPLOY_DDBPROXY }}
      HOST_NAME: ${{ vars.HOST_NAME }}
      HOST_SUB_ROUTE: ${{ vars.HOST_SUB_ROUTE }}
      LANGUAGE: ${{ vars.LANGUAGE }}
      CONTAINER_PRESERVE_CONFIG: ${{ vars.CONTAINER_PRESERVE_CONFIG }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
      FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}
      FOUNDRY_ADMIN_KEY: ${{ secrets.FOUNDRY_ADMIN_KEY }}

  deploy-aci:
    if: vars.Type == 'ACI'
    uses: ./.github/workflows/deploy-aci.yml
    with:
      location: ${{ vars.LOCATION }}
      BASE_RESOURCE_NAME: ${{ vars.BASE_RESOURCE_NAME }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      STORAGE_CONFIGURATION: ${{ vars.STORAGE_CONFIGURATION }}
      CONTAINER_CONFIGURATION: ${{ vars.CONTAINER_CONFIGURATION }}
      HOST_NAME: ${{ vars.HOST_NAME }}
      HOST_SUB_ROUTE: ${{ vars.HOST_SUB_ROUTE }}
      LANGUAGE: ${{ vars.LANGUAGE }}
      CONTAINER_PRESERVE_CONFIG: ${{ vars.CONTAINER_PRESERVE_CONFIG }}
    secrets:
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      FOUNDRY_USERNAME: ${{ secrets.FOUNDRY_USERNAME }}
      FOUNDRY_PASSWORD: ${{ secrets.FOUNDRY_PASSWORD }}
      FOUNDRY_ADMIN_KEY: ${{ secrets.FOUNDRY_ADMIN_KEY }}
